version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: djangowebtest
    container_name: django-web
    restart: unless-stopped
    working_dir: /usr/src/app
    networks:
      - django-docker
    volumes:
          - ./app:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    command: tail -f /dev/null
#    command: python manage.py runserver 0.0.0.0:8000 # to run the the python server directly when container starts
  db:
    image: mysql
    container_name: django-mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=django-test
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=jethax
    networks:
      - django-docker
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
networks:
  django-docker:
    driver: bridge
